require 'securerandom'

puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
puts SecureRandom.uuid.inspect
